deepequal: proper reuse of deepequal method of referenced types
cilium/deepequal-gen pull request #4
Opened 2023-03-29 10:40 UTC by mhofstetter

This change introduces proper reuse of the DeepEqual method when being referenced from another type - even if the referenced method gets generated in the same generation run.

Without this change reuse miss the occurances which haven't been generated yet.

2023-03-29 10:42 UTC, mhofstetter commented
@aanm :eyes:

2023-03-30 11:00 UTC, aanm requested changes

2023-03-30 11:00 UTC, aanm commented on output_tests/otherpkg/c.go
> +	BoolField bool
Can we have a test with all primitives and embedded structs that also have primitives? Also a struct that has embedded structs and those structs have a pointer.

2023-03-30 11:23 UTC, mhofstetter commented on output_tests/otherpkg/c.go
> +	BoolField bool
something like this? https://github.com/cilium/deepequal-gen/pull/4/commits/389fc34fe6d178af661a8e4ca8b1d7734534b9e6

2023-03-30 13:46 UTC, aanm approved these changes

2023-03-30 13:48 UTC, merged